image: cypress/browsers:node-20.12.0-chrome-123.0.6312.86-1-ff-124.0.2-edge-123.0.2420.65-1

stages:
  - test

workflow:
  rules:
    # run MERGE REQUEST PIPELINE if a merge request is created/updated
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    # don't run BRANCH PIPELINE if a MR is already opened on this branch
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    # run BRANCH PIPELINE if a commit is pushed on any branch
    - if: '$CI_COMMIT_BRANCH'

lighthouse:
  allow_failure: false
  script:
    - npm install
    - npm run build
    - npm run lighthouse
  stage: test
  rules:
    # run MERGE REQUEST PIPELINE if a merge request is created/updated
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    # run BRANCH PIPELINE if a commit is pushed on main
    - if: '$CI_COMMIT_BRANCH == "main"'